version: '3.9'

networks:
  internal:

services:
  todos:
    container_name: todos
    image: ghcr.io/rmvs/django-microservices-todos:latest
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.http.routers.todos.rule=Host(`todos.dev`)
        - traefik.http.services.todos-service.loadbalancer.server.port=8080
      placement:
        constraints:
           - node.role == worker
    # build:
    #   context: ./todos
    networks:
      - internal
  users:
    container_name: users
    image: ghcr.io/rmvs/django-microservices-users:latest
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.http.routers.users.rule=Host(`users.dev`)
        - traefik.http.services.users-service.loadbalancer.server.port=8081
      placement:
        constraints:
           - node.role == worker
    networks:
      - internal